# Generated by Django 3.0.8 on 2020-07-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200722_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'paths',
            },
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userid',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='on_notification',
            new_name='is_notified',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phone_no',
            new_name='phone_number',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('address_detail', models.CharField(max_length=100)),
                ('requirement', models.CharField(max_length=100)),
                ('is_default', models.BooleanField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Users')),
            ],
            options={
                'db_table': 'shippings',
            },
        ),
        migrations.CreateModel(
            name='Path_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_lists', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Path')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Users')),
            ],
            options={
                'db_table': 'path_results',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Gender'),
        ),
    ]
