# Generated by Django 3.0.8 on 2020-07-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200723_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='gender',
            new_name='gender_type',
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
