# Generated by Django 3.0.8 on 2020-07-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200728_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart_at',
            field=models.DateTimeField(null=True),
        ),
    ]
