# Generated by Django 3.0.8 on 2020-07-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_cart_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
