# Generated by Django 3.0.8 on 2020-07-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BladeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'blade_products',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='RazorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
            options={
                'db_table': 'razor_products',
            },
        ),
        migrations.CreateModel(
            name='RazorProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'razor_products_colors',
            },
        ),
        migrations.CreateModel(
            name='SkinProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
            options={
                'db_table': 'skin_products',
            },
        ),
        migrations.CreateModel(
            name='SkinProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'skin_products_sizes',
            },
        ),
        migrations.RemoveField(
            model_name='productcolors',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcolors',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cartimage',
            name='products_colors',
        ),
        migrations.RemoveField(
            model_name='cartimage',
            name='products_size',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductColors',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='skinproductsize',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Size'),
        ),
        migrations.AddField(
            model_name='skinproductsize',
            name='skin_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SkinProduct'),
        ),
        migrations.AddField(
            model_name='razorproductcolor',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Color'),
        ),
        migrations.AddField(
            model_name='razorproductcolor',
            name='razor_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.RazorProduct'),
        ),
        migrations.AddField(
            model_name='bladeproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category'),
        ),
        migrations.AddField(
            model_name='cartimage',
            name='blade_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.BladeProduct'),
        ),
        migrations.AddField(
            model_name='cartimage',
            name='razor_products_colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.RazorProductColor'),
        ),
        migrations.AddField(
            model_name='cartimage',
            name='skin_products_sizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SkinProductSize'),
        ),
    ]
