# Generated by Django 3.0.8 on 2020-07-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200722_2059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartImage',
            new_name='OrderImage',
        ),
        migrations.AlterModelTable(
            name='orderimage',
            table='order_images',
        ),
    ]
