# Generated by Django 3.0.8 on 2020-07-24 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200723_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'skin_types',
            },
        ),
        migrations.RemoveField(
            model_name='bladeproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='name',
        ),
        migrations.AddField(
            model_name='productsize',
            name='skin_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SkinType'),
        ),
    ]
