# Generated by Django 3.0.8 on 2020-07-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsize_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
