# Generated by Django 3.0.8 on 2020-07-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_size_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='description',
        ),
    ]
