# Generated by Django 3.0.8 on 2020-07-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_orderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ManyToManyField(through='products.ProductColor', to='products.Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(through='products.ProductSize', to='products.Size'),
        ),
        migrations.AlterField(
            model_name='skintype',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
