# Generated by Django 3.0.8 on 2020-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_razorcolor_eng_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorcolor',
            name='eng_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
